### ISSUE TITLE
Configuration defaults documentation

### ISSUE THREAD

**Issue by ttshivers** [ahmadnassri/action-dependabot-auto-merge#14]
In the new version, a config file was introduced `.github/auto-merge.yml`. It would be helpful to have some documentation about what the default state is. For example, it appears that the default state is to not auto merge non security critical updates.

**Comment by AlCalzone** [comment]
The default state should be merging all updates that match the `target` input, which is `patch` by default - so just like it used to.

However, the new version is still a bit buggy it seems:
https://github.com/ahmadnassri/action-dependabot-auto-merge/pull/10#issuecomment-689815823

**Comment by ahmadnassri** [comment]
added documentation on defaults here: https://github.com/ahmadnassri/action-dependabot-auto-merge/commit/3ec112738eff67df99455151cd55ce823f52dd6a

and I think the buggyness described by @AlCalzone might be due to missing checkout step, but will continue that discussion in #17
