### ISSUE TITLE
Action fails to find auto-merge.yml

### ISSUE THREAD

**Issue by AlCalzone** [ahmadnassri/action-dependabot-auto-merge#17]
With v2.0.2, the action now does what it is supposed to do, but looking at my logs, it still falls back to the default config (using workflow's "target") instead of reading `.github/auto-merge.yml`.

Any idea what might be causing this?

**Comment by ahmadnassri** [comment]
I'm still looking into this, I think I'm gonna add a mock docker environment in docker-compose to mimic the actions runtime ...

**Comment by ahmadnassri** [comment]
oh, quick question .... did you `checkout` before running this action in your workflow?

**Comment by ahmadnassri** [comment]
I've updated the doc to clearly indicate the use of `checkout` before calling this action ... let me know if that is the cause.

**Comment by AlCalzone** [comment]
Yeah, that was it 😓

**Comment by Maxim-Mazurok** [comment]
> I've updated the doc to clearly indicate the use of `checkout` before calling this action ... let me know if that is the cause.

It's not really clear from the README why we need checkout. Would be great to add this explanation. I was wondering if I need it if I don't use `auto-merge` config.
