### ISSUE TITLE
Sorry, only users with push access can use that command

### ISSUE THREAD

**Issue by bennyn** [ahmadnassri/action-dependabot-auto-merge#21]
I am using "GitHub Action: Dependabot Auto Merge" and it looks like the action sends a "@dependabot merge" comment to a PR discussion. Unfortunately, dependabot is not able to merge because it tells me that it does not have push access. 

Is there a setting that I am missing?

**Screenshot**

![image](https://user-images.githubusercontent.com/469989/93068520-e2393900-f67c-11ea-994b-eef2f3daaef6.png)

**Comment by ahmadnassri** [comment]
look for the details in the token scope under readme:

https://github.com/ahmadnassri/action-dependabot-auto-merge

tl;dr you need a personal access token with the proper scope, can't use default Action token
