### ISSUE TITLE
Will it only merge if all CI passes?

### ISSUE THREAD

**Issue by peterbe** [ahmadnassri/action-dependabot-auto-merge#3]
I'm guessing the answer is yes but I want to be absolutely sure. 
Sorry if this is more of a support question than an actual issue, but to remedy that: The README doesn't mention if this depends on CI passing entirely. :)

**Comment by ahmadnassri** [comment]
yes, thankfully this is something `@dependabot merge` does internally, so if any "check" (a.k.a jobs & steps) fail, it wont merge.

**Comment by ahmadnassri** [comment]
also, if you feel you can better indicate this in the README for another future user, a PR would be great! ❤️

**Comment by ahmadnassri** [comment]
this is bizarly not documented anywhere on github's new docs site, and dependabot's old blog posts from before acquisition have conflicting messages...

here's a screenshot of how dependabot wont merge with failed checks:

![image](https://user-images.githubusercontent.com/183195/90711173-ffd9d500-e26d-11ea-9dcb-61e59b58ef03.png)
