### ISSUE TITLE
Support question regarding auto-merge?

### ISSUE THREAD

**Issue by char0n** [ahmadnassri/action-dependabot-auto-merge#45]
I was wondering about the fact how this GitHub Action actually work.

You mention in the readme: `Note: Dependabot will wait until all your status checks pass before merging. This is a function of Dependabot itself, and not this Action.`

I did some research about what this actually means; I wonder if you can kindly confirm my findings:

If this GitHub Actions issues a `@dependabot merge` comment, dependabot then waits for any GitHub Check visible in "Checks" tab on every PR before it actually merges (it's a feature of dependabot). This is a automatic for all GitHub Actions as they implicitly integrate with Checks API. But any 3rd party GitHub App that is part of repository's CI, but doesn't integrate with Checks API - dependabot will not wait for them and merges as soon as all Checks under PR's Checks reports success. Am I right in my assumptions?

Thank you!

![image](https://user-images.githubusercontent.com/193286/102397789-a9439400-3fde-11eb-87a8-a13ff8aea6ab.png)

**Comment by ahmadnassri** [comment]
yes, your description is correct and accurate.

**Comment by char0n** [comment]
@ahmadnassri thanks for confirming!
