### ISSUE TITLE
TypeError: Cannot read property 'owner' of undefined

### ISSUE THREAD

**Issue by peterbe** [ahmadnassri/action-dependabot-auto-merge#5]
See https://github.com/mdn/yari/pull/1152/checks?check_run_id=1012806139
on [this PR](https://github.com/mdn/yari/pull/1152)

```
Run ahmadnassri/action-dependabot-auto-merge@v1
/usr/bin/docker run --name ahmadnassriactiondependabotautomergev1_4f96b1 --label 8118cb --workdir /github/workspace --rm -e INPUT_GITHUB-TOKEN -e INPUT_TARGET -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/yari/yari":"/github/workspace" ahmadnassri/action-dependabot-auto-merge:v1
title: "Bump mdn-browser-compat-data from 1.0.34 to 1.0.35"
from: 1.0.34
to: 1.0.35
dependency update target is "patch", found "patch", will auto-merge
##[error]Unhandled error: TypeError: Cannot read property 'owner' of undefined
```

The workflow is here: https://github.com/mdn/yari/blob/master/.github/workflows/auto-merge.yml

**Comment by peterbe** [comment]
Thanks for fixing that.

Also, perhaps I'm just not able to understand the instructions but what do I need to do to make the merge allowed?
`dependabot` is [rejecting attempts to merge](https://github.com/mdn/yari/pull/1156) because `github-actions[bot]` doesn't have doesn't have the "push access".

**Comment by ahmadnassri** [comment]
@peterbe by default the action uses the `github.token` provided by GitHub which has a strict set of permissions ... 

as you can see this results in the "user" being "github-actions"
![image](https://user-images.githubusercontent.com/183195/91082482-b8a96680-e616-11ea-8faa-0fc3696efe97.png)

which is not a real user ... you should specify a github token to use using `github-token`

```
steps:
  - uses: ahmadnassri/action-dependabot-auto-merge@v1
    with:
      target: patch
      github-token: ${{ secrets.mytoken }}
```

**Comment by ahmadnassri** [comment]
alternatively configuring the git environment in checkout step to specify the active user: https://github.com/actions/checkout

**Comment by peterbe** [comment]
If I generate a personal access token, will auto-merge and Dependbot merge all PRs as `@peterbe`?

Prior, when we used the old Dependabot service which could auto-merge itself, we would get it as the committer in the [git commit history](https://github.com/mdn/yari/commits/master). If I use my own personal access token, will it all appear as if I committed those?

**Comment by ahmadnassri** [comment]
this action is not making the commits itself. the commits are done in dependabot itself (with the `@dependabot merge`) command 

the token referenced here is one used to simply post the instructions to dependabot (i.e. the `@dependabot merge` command) which dependabot checks to see if it's an account with merge permissions and thus can obey it's instructions ...

**Comment by peterbe** [comment]
Ok. I think I get it now. (sorry for being dim)
If `auto-merge` writes the comment `@dependabot merge` it gets refused. But if **I** do it, the Dependabot is OK with it. 
And the merge commit will be in the name of the Dependabot bot. 
So I need to give the `auto-merge` action, my personal access token but it won't be merged as me. 

By the way, is there a way to do `@dependabot squash and merge` instead of `@dependabot merge`?

**Comment by ahmadnassri** [comment]
good idea ... now available in [v1.2.0](https://github.com/ahmadnassri/action-dependabot-auto-merge/releases/tag/v1.2.0) (also released as `v1`

you can add `command` and `approve` flags to the inputs to further customize functionality, see README for details

**Comment by peterbe** [comment]
Not sure if it's related but I created a personal access token (no scopes) and added it as a secret on the repo.
But now I get:
```
##[error]Not Found
HttpError: Not Found
    at /action/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async approve (file:///action/lib/api.js:2:28)
    at async default (file:///action/lib/index.js:31:25)
    at async file:///action/index.js:25:1
```
See https://github.com/mdn/yari/pull/1164/checks?check_run_id=1027860862

**Comment by peterbe** [comment]
Actually, I don't think I understand that new `approve` option. Doesn't there need to be a review request first?

**Comment by ahmadnassri** [comment]
re: reviews, depends on your repo configuration ... if you configure the repo to now allow merging without approval, then dependabot won't be able to merge it ...

if you don't have that enabled, then it's harmless, just makes it so that the PR is marked as approved at the same time (and with the same user) before posting the dependabot command

**Comment by ahmadnassri** [comment]
as for the error, I'm investigating... I thought I added all tests needed, but clearly I missed something

**Comment by ahmadnassri** [comment]
I'm unable to replicate what is causing that 404 error ... however I did add debug logging that should help surface the issue ... you will need to [enable debugging](https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging) to see the debug logs (and re-run the job)

let me know when you get them.

**Comment by peterbe** [comment]
I set debugging on so you can now download all the log files. 
I think it's public if you want to take a look https://github.com/mdn/yari/pull/1164/checks?check_run_id=1027907794
It's the same error still. 
Not sure what else to try at this point.

**Comment by ahmadnassri** [comment]
@peterbe can you re-run that job? it still shows the result from 21 hours ago, which means the debug logs are not visible

**Comment by peterbe** [comment]
> @peterbe can you re-run that job? it still shows the result from 21 hours ago, which means the debug logs are not visible
> 
Weird. I thought I did that. 
Foolishly I ran [`@dependabot recreate`](https://github.com/mdn/yari/pull/1164#issuecomment-680947247) when I should have used the "Re-run jobs" button in Actions. 

> thank you for helping to debug this issue

Thank YOU for helping!

**Comment by peterbe** [comment]
[Now it has downloadable detailed logs](https://github.com/mdn/yari/pull/1164/checks?check_run_id=1032234291)

**Comment by ahmadnassri** [comment]
which debug flag did you enable? apparently there are two different ones! `ACTIONS_STEP_DEBUG ` is needed for step debugging 

I do not see the debug logs from the actions step in the downloaded logs, so I'm assuming you enabled `ACTIONS_RUNNER_DEBUG` but not `ACTIONS_STEP_DEBUG` ...

/me grumbles something about GH Actions Dev Experience

**Comment by peterbe** [comment]
Set now: 
<img width="962" alt="Screen Shot 2020-08-27 at 11 24 58 AM" src="https://user-images.githubusercontent.com/26739/91462268-01039700-e858-11ea-9b75-eddd92162983.png">
*/me giggles at the fact I just took a screenshot of my "Secrets" and shared publicly*

**Comment by ahmadnassri** [comment]
thank you, now you have to `@dependabot recreate` again :)

**Comment by peterbe** [comment]
> thank you, now you have to `@dependabot recreate` again :)

I used `rebase` but it seems to have triggered a build, which still fails :( https://github.com/mdn/yari/pull/1164/checks?check_run_id=1037331481

**Comment by peterbe** [comment]
Do the log files make sense now? Anything juicy?

**Comment by ahmadnassri** [comment]
apologies, i'm multi-tasking .. yes, this is what I'm looking for: 

![image](https://user-images.githubusercontent.com/183195/91467449-94d86180-e85e-11ea-87e4-81c157a3b501.png)

I'll look deeper now

**Comment by ahmadnassri** [comment]
I pushed [`v1.2.3`](https://github.com/ahmadnassri/action-dependabot-auto-merge/releases/tag/v1.2.3) which ... i'm not confident will fix this, but it reverts that section of the code back to previous state where this wasn't an issue ...

everything about that looks correct and matches the [API documentation](https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request)

could you please recreate that PR and see if the revert fixed it (which would be puzzling, and perhaps a bug in GH own API docs)

**Comment by ahmadnassri** [comment]
I even made a DIRECT http call using that same URL / body to the SAME repo ... and of course because it's public, it accepted my review: 

![image](https://user-images.githubusercontent.com/183195/91469697-b5ee8180-e861-11ea-9fc0-164c9afc9529.png)

![image](https://user-images.githubusercontent.com/183195/91469708-bab33580-e861-11ea-9cbb-2aad9b8cd6d4.png)

so the fact that the approve API call didn't work in code ... is weird!

**Comment by ahmadnassri** [comment]
and if the token was bad / not provided, it would have responded with a 401

![image](https://user-images.githubusercontent.com/183195/91469808-e504f300-e861-11ea-814a-8003d5be026d.png)

the plot thickens ... but awaiting your test result

**Comment by peterbe** [comment]
[`@dependabot recreate` triggered](https://github.com/mdn/yari/pull/1164#issuecomment-682078735) 
lets see!

**Comment by peterbe** [comment]
Looks like it's the same error: https://github.com/mdn/yari/pull/1164/checks?check_run_id=1037331481

**Comment by ahmadnassri** [comment]
this is frustrating and weird ...

can you try recreating / rebasing this PR: https://github.com/mdn/yari/pull/1161

**Comment by peterbe** [comment]
> this is frustrating and weird ...
> 
Hopefully, we're both learning from all of this. 

> can you try recreating / rebasing this PR: [mdn/yari#1161](https://github.com/mdn/yari/pull/1161)
[Done](https://github.com/mdn/yari/pull/1161#issuecomment-682099609)

**Comment by ahmadnassri** [comment]
happy Friday!

I added [further debugging](https://github.com/ahmadnassri/action-dependabot-auto-merge/commit/e099c91c25ccfc81a4bbe161acc322fdff748d26) this time with headers ...

if this doesn't surface the issue, I am stuck.

worth noting: it has been working non-stop for me across two private orgs and in public repos, here's a public one: https://github.com/ahmadnassri/action-semantic-release/pull/4

**Comment by peterbe** [comment]
I just trigged a [recreate](https://github.com/mdn/yari/pull/1161) again. I hope that will unleash some clues. 

Between use dev nerds, it would be nice to know what's going on and let's hope we win that game. 

But could it be something wrong with how I'm using it? Like, have I done something wrong how I'm using secrets? Perhaps there's something else that happens long before and a long-tail aftereffect is that it's trying to do some HTTP call that it shouldn't even have done. 

* I created a secret called `AUTOMERGE_TOKEN` and its value is a Personal Access Token (in my name) without any scopes associated. 
* I'm using it [right here like this](https://github.com/mdn/yari/blob/0f25d1ca46bf1300863f9dd05a5e6dbe7ae3101b/.github/workflows/auto-merge.yml#L13)

Not sure what else it would be. To be honest I'm still not sure I understand [the usage example](https://github.com/ahmadnassri/action-dependabot-auto-merge#usage) because how could that ever work if you don't supply a token.

**Comment by peterbe** [comment]
Still, but now with more debugging:
```
 ##[error]Not Found
HttpError: Not Found
    at /action/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async approve (file:///action/lib/api.js:2:3)
    at async default (file:///action/lib/index.js:33:5)
    at async file:///action/index.js:35:1
##[debug]POST https://api.github.com/repos/mdn/yari/pulls/1161/reviews
##[debug]
##[debug]{
##[debug]  accept: 'application/vnd.github.v3+json',
##[debug]  'user-agent': 'octokit-core.js/3.1.2 Node.js/14.8.0 (linux; x64)',
##[debug]  authorization: 'token [REDACTED]',
##[debug]  'content-type': 'application/json; charset=utf-8'
##[debug]}
##[debug]
##[debug]'{"event":"APPROVE","body":"@dependabot squash and merge"}'
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run ahmadnassri/action-dependabot-auto-merge@v1
```

To be honest, I don't understand how the action relates to reviews and stuff but I didn't realize until now that it fails BEFORE the other tests have run. I snapped this screenshot:
<img width="953" alt="Screen Shot 2020-08-28 at 12 53 16 PM" src="https://user-images.githubusercontent.com/26739/91593365-03d0bb80-e92e-11ea-9d28-75d834911127.png">

Which is curious because why `POST` something for `pulls/1161/reviews` in the first place?
It could perhaps make sense to `POST` a review *after* all the other CI have passed and *if* `action-dependabot-auto-merge` is configured to `approve`.

**Comment by peterbe** [comment]
By the way, in github.com/mdn/yari we haven't enabled that PRs must be approved before you can press the green merge button. So we generally, as a team, just use the review requests and reviews as a "human level" check. 
Do you think that matters?

By the way, I don't think I like this action to approve and reviews. It's a bot and it won't have reviewed the code (to be perfectly technical). The bot will have checked some stuff, but will not have made a review. 
So for this repo, I could set `approve:false` in your .yml. But that might distract from the debugging.

**Comment by ahmadnassri** [comment]
hmm yeah, try `approve:false`

**Comment by ahmadnassri** [comment]
> Between use dev nerds, it would be nice to know what's going on and let's hope we win that game.

💯

**Comment by ahmadnassri** [comment]
> But could it be something wrong with how I'm using it

your setup looks correct, and if it was a token issue, it would have responded with `401`

**Comment by ahmadnassri** [comment]
> Not sure what else it would be. To be honest I'm still not sure I understand the usage example because how could that ever work if you don't supply a token.

yeah, the examples need to be updated to properly reflect the need for token

**Comment by ahmadnassri** [comment]
> To be honest, I don't understand how the action relates to reviews and stuff but I didn't realize until now that it fails BEFORE the other tests have run. I snapped this screenshot:

yes it fails before because it's a separate "workflow" in GitHub Action, thus it runs in parallel, there is no cascading workflow dependencies, or sequencing them in GitHub Actions ... but that's fine because:

> It could perhaps make sense to POST a review after all the other CI have passed and if action-dependabot-auto-merge is configured to approve.

it wouldn't matter when this action does it's thing, as the **execution** of the merge is done by Dependabot app, and that _DOES_ wait for all the checks to finish running, _AND_ for them all to be successful

**Comment by ahmadnassri** [comment]
> So for this repo, I could set approve:false in your .yml. But that might distract from the debugging.

there is now a code split that follows the review flag ... if you set it to `false` and it works, I'm happy to see you declare success and head into the weekend with weight off your mind ...

**Comment by peterbe** [comment]
[Same old error](https://github.com/mdn/yari/pull/1161/checks?check_run_id=1042942603). Any useful debug logging there?

**Comment by ahmadnassri** [comment]
seems like it still went down the approve path ... fixed it [here](https://github.com/ahmadnassri/action-dependabot-auto-merge/commit/676039788a1b29841cec56e0cf923e7882b4bec6) ... 

/me cries

**Comment by peterbe** [comment]
Any new hopes?

**Comment by ahmadnassri** [comment]
oh hey! we have a new error now!

![image](https://user-images.githubusercontent.com/183195/91906689-a06cc380-ec76-11ea-9050-201ca5ee591e.png)

**Comment by ahmadnassri** [comment]
which ... makes ABSOLUTELY NO SENSE WHATSOEVER!

the command is just "comment" ... why does it need "admin" rights!?

https://github.com/ahmadnassri/action-dependabot-auto-merge/blob/master/action/lib/api.js#L11

**Comment by ahmadnassri** [comment]
according to a thread in the github community forum of a similar error:

>  It was because the personal access token didn’t have not enough scope (public_repo).

https://github.community/t/why-does-github-api-require-admin-rights-to-leave-a-comment-on-a-pr/300

**Comment by ahmadnassri** [comment]
this suddenly makes a lot of sense .. the 404 before and the "admin" requirement now ... the GitHub API is badly designed and produces terribly uninformative error messages ... I think setting the correct scopes in your token will take care of this ... 

the scopes needed should be `repo` for private repos, and `public_repo` for public repos ... I'll update the docs once you confirm your token was updated and re-running the workflow succeeds

**Comment by peterbe** [comment]
[IT WORKS!!!!](https://github.com/mdn/yari/pull/1164)

**Comment by peterbe** [comment]
The magic right here!
<img width="767" alt="Screen Shot 2020-09-01 at 9 49 57 PM" src="https://user-images.githubusercontent.com/26739/91923727-0d944f00-ec9f-11ea-8d39-d9c6484e1eca.png">

**Comment by peterbe** [comment]
THANK YOU for all your hard work. I'm going to remove the debugging secrets now. 

By the way, do you know if it's possible to use something other than my personal access token? It works well, but it would be cool if it was a **bot** that told Dependabot to merge and not this "peterbe" rando.

**Comment by ahmadnassri** [comment]
huzzah! 🎉 🎉 🎉 🎉 🎉 🎉 

I will update the README with all this info next.

> By the way, do you know if it's possible to use something other than my personal access token?

that's my one big ~wtf~ wish list item for GitHub ... their official advise is to create a new user, call it a bot account and use it for such functionality .... which is ... sad.

they will charge you for the extra user if you're a private org AND they might block it for "bot" only behaviour against their API ... so good luck!

so, what I do today for private orgs:

- created an account that is only used for token management, so that:
- the comments / commits / actions are not shown to be done by a person, to avoid the "hey did you do X?" questions
- the history / audit log of activity is clearly shown
- rotating keys as a monthly task becomes easier, when you share the login to that bot account within the security / devops team
