### ISSUE TITLE
Not merging depenednet bot pull request even though there isn't any errors

### ISSUE THREAD

**Issue by irohitb** [ahmadnassri/action-dependabot-auto-merge#54]
I was trying to implement `action-dependabot-auto-merge` [github action][1] to automatically merge pull request in github for one of [my repo][2]

This is my workflow file 

    name: auto-merge
    
    on:
      pull_request:
    
    jobs:
      auto-merge:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: ahmadnassri/action-dependabot-auto-merge@v2
            with:
              github-token: ${{ secrets.BLENDTALE_GITHUB_BOT }}

But for some reason, it isn't merging in master. git shows that action [ran successfully.][3] 

Any idea what I might be doing wrong? 

  [1]: https://github.com/ahmadnassri/action-dependabot-auto-merge
  [2]: https://github.com/blendtale/react-native-keyboard-view-space
  [3]: https://github.com/blendtale/react-native-keyboard-view-space/actions

**Comment by ahmadnassri** [comment]
you didn't provide a config file, so the default config applied, in this case the change was a major change (husky from 4.3.8 to 5.1.0) so as per the default config, it will require manual merging ...

the details are printed in the log output of the action.

you can add a config file to change this behaviour

**Comment by ahmadnassri** [comment]
I'm closing this issue, unless you have any more details to add, hopefully the config solved your problem
