### ISSUE TITLE
Marketplace is not updated with the latest version

### ISSUE THREAD

**Issue by runephilosof-abtion** [ahmadnassri/action-dependabot-auto-merge#55]
https://github.com/marketplace/actions/dependabot-auto-merge
![image](https://user-images.githubusercontent.com/57357936/108812008-9933cc00-75ae-11eb-9f48-43d3c34624b0.png)

The badge and https://github.com/ahmadnassri/action-dependabot-auto-merge/releases shows v2.3.1 as the latest version but on the Github marketplace it says 2.2.0.

**Comment by ahmadnassri** [comment]
I've updated the market place version.

this action is automatically versioned and released, and unfortunately listing the version on the marketplace is a manual step.

that said, as per the docs, if you use `@v2` you'll get the most recent version anyways (see the tags in the repo)

thanks for notifying me though
