### ISSUE TITLE
Warning: no version range detected in PR title

### ISSUE THREAD

**Issue by SeenNotHurd** [ahmadnassri/action-dependabot-auto-merge#57]
I'm getting this warning (Which then stops merging) quite a lot, even though there is (to my understanding) a version range in the PR title, in the latest case it was 9.4 -> 9.4.2. Is there something wrong in the setup? The composer file in this instance has ^9.0.2 as the version constraint.

Any help would be great, and thanks for maintaining this 🙏

**Comment by ahmadnassri** [comment]
can you paste the full output of the action to see more detail?

**Comment by ahmadnassri** [comment]
it might be related to this #36

**Comment by SeenNotHurd** [comment]
Ahhh yes this seems to be related to #36, I'll close this issue then and follow that one 👍 

Is there some help I could give to helping that issue along?
