### ISSUE TITLE
Rebase and merge

### ISSUE THREAD

**Issue by ttshivers** [ahmadnassri/action-dependabot-auto-merge#8]
Is there a way to get dependabot to use the "rebase and merge" strategy when auto merging so that merge commit messages aren't created? I can't seem to find a config option in dependabot for this.

**Comment by ahmadnassri** [comment]
you can either modify your repo setting to only allow that strategy and dependabot will follow, or you can pass the following in your workflow file:

```yaml
with:
  command: squash and merge
```

**Comment by ttshivers** [comment]
Thank you
